server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: murari
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Disable Flyway for initial development
  # Enable later when database scripts are ready
  flyway:
    enabled: false

  # Redis configuration
  # Keep this only if your auth module uses Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms


# Eureka Discovery Server
# For local IntelliJ testing use localhost
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka123}@localhost:8761/eureka/


# Application custom configuration
app:

  jwt:
    # Temporary key for development
    # Later move this to environment variables
    secret: myverysecretkeymyverysecretkey123456789

    # 24 hours
    expiration-ms: 86400000

    # 30 days refresh token
    refresh-expiration-ms: 2592000000


  internal:
    api-key: cardpro-secret-key


# Actuator monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always