-- Baseline: the `users` table owned by user-service.
--
-- Before Flyway was adopted, this schema was created by Hibernate
-- (spring.jpa.hibernate.ddl-auto=update), so on existing environments the
-- table may already be present. CREATE TABLE IF NOT EXISTS makes this
-- migration a no-op there, while still producing the full base schema on a
-- fresh database.
CREATE TABLE IF NOT EXISTS users (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                       VARCHAR(255) NOT NULL UNIQUE,
    first_name                  VARCHAR(255) NOT NULL,
    last_name                   VARCHAR(255) NOT NULL,
    display_name                VARCHAR(255),
    job_title                   VARCHAR(255),
    phone_number                VARCHAR(255),
    profile_image               VARCHAR(255),
    role                        VARCHAR(255) NOT NULL,
    active                      BOOLEAN NOT NULL DEFAULT TRUE,
    is_pro                      BOOLEAN NOT NULL DEFAULT FALSE,
    email_notifications_enabled BOOLEAN,
    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP
);
